spring:
  application:
    name: upb-employees
  datasource:
    url: jdbc:mysql://localhost:3306/upb_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
